const fs = require('fs');
const path = require('path');

const code = [
`import { test, expect, type Page } from '@playwright/test';

const BASE = 'http://localhost:3000';
let testEmail = 'e2e_' + Date.now() + '@test.com';
const testPass = 'TestPass123!';
const testName = 'E2E User';

async function register(p: Page) {
  await p.goto(BASE + '/en/register');
  await p.waitForSelector('#name', { timeout: 15000 });
  await p.fill('#name', testName);
  await p.fill('#email', testEmail);
  await p.fill('#password', testPass);
  await p.fill('#confirmPassword', testPass);
  await p.click('button[type="submit"]');
  await p.waitForURL('**/en/login', { timeout: 10000 });
}

async function login(p: Page) {
  await p.goto(BASE + '/en/login');
  await p.waitForSelector('#email', { timeout: 15000 });
  await p.fill('#email', testEmail);
  await p.fill('#password', testPass);
  await p.click('button[type="submit"]');
  await p.waitForURL('**/en/dashboard', { timeout: 15000 });
}`,
"",
"// 1. ROOT REDIRECT",
"test('1.1 / redirects to /en', async ({ page }) => {",
"  await page.goto(BASE);",
"  await page.waitForURL('**/en*', { timeout: 10000 });",
"  expect(page.url()).toContain('/en');",
"});",
"",
"// 2. REGISTER PAGE",
"test.describe('2. Register', () => {",
"  test('2.1 renders all fields', async ({ page }) => {",
"    await page.goto(BASE + '/en/register');",
"    await expect(page.locator('#name')).toBeVisible();",
"    await expect(page.locator('#email')).toBeVisible();",
"    await expect(page.locator('#password')).toBeVisible();",
"    await expect(page.locator('#confirmPassword')).toBeVisible();",
"  });",
"",
"  test('2.2 mismatched passwords error', async ({ page }) => {",
"    await page.goto(BASE + '/en/register');",
"    await page.waitForSelector('#name');",
"    await page.fill('#name', 'Test');",
"    await page.fill('#email', 'mismatch_' + Date.now() + '@t.com');",
"    await page.fill('#password', 'Password123!');",
"    await page.fill('#confirmPassword', 'Different123!');",
"    await page.click('button[type=\"submit\"]');",
"    await page.waitForSelector('.text-destructive', { timeout: 5000 });",
"  });",
"",
"  test('2.3 short password error', async ({ page }) => {",
"    await page.goto(BASE + '/en/register');",
"    await page.waitForSelector('#name');",
"    await page.fill('#name', 'Short');",
"    await page.fill('#email', 'short_' + Date.now() + '@t.com');",
"    await page.fill('#password', 'abc');",
"    await page.fill('#confirmPassword', 'abc');",
"    await page.click('button[type=\"submit\"]');",
"    await page.waitForSelector('.text-destructive', { timeout: 5000 });",
"  });",
"",
"  test('2.4 has login link', async ({ page }) => {",
"    await page.goto(BASE + '/en/register');",
"    await expect(page.locator('a[href*=\"login\"]')).toBeVisible();",
"  });",
"",
"  test('2.5 registers successfully', async ({ page }) => {",
"    testEmail = 'e2e_' + Date.now() + '@test.com';",
"    await register(page);",
"    expect(page.url()).toContain('/en/login');",
"  });",
"",
"  test('2.6 duplicate email error', async ({ page }) => {",
"    await page.goto(BASE + '/en/register');",
"    await page.waitForSelector('#name');",
"    await page.fill('#name', 'Dup');",
"    await page.fill('#email', testEmail);",
"    await page.fill('#password', testPass);",
"    await page.fill('#confirmPassword', testPass);",
"    await page.click('button[type=\"submit\"]');",
"    await page.waitForSelector('.text-destructive', { timeout: 5000 });",
"  });",
"});",
"",
"// 3. LOGIN PAGE",
"test.describe('3. Login', () => {",
"  test('3.1 renders fields', async ({ page }) => {",
"    await page.goto(BASE + '/en/login');",
"    await expect(page.locator('#email')).toBeVisible();",
"    await expect(page.locator('#password')).toBeVisible();",
"  });",
"",
"  test('3.2 wrong credentials error', async ({ page }) => {",
"    await page.goto(BASE + '/en/login');",
"    await page.waitForSelector('#email');",
"    await page.fill('#email', 'wrong@test.com');",
"    await page.fill('#password', 'WrongPass!');",
"    await page.click('button[type=\"submit\"]');",
"    await page.waitForSelector('.text-destructive', { timeout: 5000 });",
"  });",
"",
"  test('3.3 has register link', async ({ page }) => {",
"    await page.goto(BASE + '/en/login');",
"    await expect(page.locator('a[href*=\"register\"]')).toBeVisible();",
"  });",
"",
"  test('3.4 logs in successfully', async ({ page }) => {",
"    await login(page);",
"    expect(page.url()).toContain('/en/dashboard');",
"  });",
"});",
"",
"// 4. AUTH GUARD",
"test('4.1 unauthenticated redirects to login', async ({ page }) => {",
"  await page.goto(BASE + '/en/dashboard');",
"  await page.waitForURL('**/login**', { timeout: 10000 });",
"  expect(page.url()).toContain('login');",
"});",
"",
"// 5. DASHBOARD",
"test.describe('5. Dashboard', () => {",
"  test.beforeEach(async ({ page }) => { await login(page); });",
"",
"  test('5.1 renders with content', async ({ page }) => {",
"    await page.waitForTimeout(3000);",
"    const body = await page.textContent('body');",
"    expect(body!.length).toBeGreaterThan(50);",
"  });",
"",
"  test('5.2 has sidebar nav links', async ({ page }) => {",
"    await page.waitForTimeout(1000);",
"    const links = page.locator('aside a');",
"    expect(await links.count()).toBeGreaterThanOrEqual(5);",
"  });",
"});",
"",
"// 6. NAVIGATION - all pages load",
"test.describe('6. Navigation', () => {",
"  test.beforeEach(async ({ page }) => { await login(page); });",
"  const routes = ['dashboard','meals','recipes','body','analytics','fasting','medical','notifications','settings'];",
"  for (const r of routes) {",
"    test('6.x navigates to ' + r, async ({ page }) => {",
"      await page.goto(BASE + '/en/' + r);",
"      await page.waitForLoadState('networkidle', { timeout: 15000 });",
"      expect(page.url()).toContain(r);",
"    });",
"  }",
"});",
"",
"// 7. MEALS PAGE",
"test.describe('7. Meals', () => {",
"  test.beforeEach(async ({ page }) => {",
"    await login(page);",
"    await page.goto(BASE + '/en/meals');",
"    await page.waitForLoadState('networkidle', { timeout: 15000 });",
"  });",
"  test('7.1 has meal tabs', async ({ page }) => {",
"    expect(await page.locator('[role=\"tab\"]').count()).toBeGreaterThanOrEqual(3);",
"  });",
"  test('7.2 has search input', async ({ page }) => {",
"    await expect(page.locator('input').first()).toBeVisible();",
"  });",
"  test('7.3 food search works', async ({ page }) => {",
"    await page.locator('input').first().fill('rice');",
"    await page.waitForTimeout(1000);",
"  });",
"  test('7.4 switch meal tabs', async ({ page }) => {",
"    const tabs = page.locator('[role=\"tab\"]');",
"    if (await tabs.count() > 1) await tabs.nth(1).click();",
"  });",
"});",
"",
"// 8. BODY MEASUREMENTS",
"test.describe('8. Body', () => {",
"  test.beforeEach(async ({ page }) => {",
"    await login(page);",
"    await page.goto(BASE + '/en/body');",
"    await page.waitForLoadState('networkidle', { timeout: 15000 });",
"  });",
"  test('8.1 renders heading', async ({ page }) => {",
"    await expect(page.locator('h1').first()).toBeVisible();",
"  });",
"  test('8.2 has add measurement button', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /add/i }).first();",
"    await expect(btn).toBeVisible();",
"  });",
"  test('8.3 add button shows form', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /add/i }).first();",
"    await btn.click();",
"    await expect(page.locator('#weight')).toBeVisible();",
"  });",
"  test('8.4 form has all 8 inputs', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /add/i }).first();",
"    await btn.click();",
"    for (const id of ['weight','bodyFat','waist','hip','bicep','chest','thigh','neck']) {",
"      await expect(page.locator('#' + id)).toBeVisible();",
"    }",
"  });",
"  test('8.5 saves measurement', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /add/i }).first();",
"    await btn.click();",
"    await page.fill('#weight', '75');",
"    await page.fill('#bodyFat', '18');",
"    await page.fill('#waist', '82');",
"    await page.fill('#hip', '96');",
"    await page.locator('button[type=\"submit\"]').first().click();",
"    await page.waitForTimeout(2000);",
"  });",
"  test('8.6 cancel hides form', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /add/i }).first();",
"    await btn.click();",
"    await expect(page.locator('#weight')).toBeVisible();",
"    await page.locator('button').filter({ hasText: /cancel/i }).first().click();",
"    await expect(page.locator('#weight')).not.toBeVisible();",
"  });",
"  test('8.7 body visualization SVG exists', async ({ page }) => {",
"    expect(await page.locator('svg').count()).toBeGreaterThan(0);",
"  });",
"});",
"",
"// 9. RECIPES PAGE",
"test.describe('9. Recipes', () => {",
"  test.beforeEach(async ({ page }) => {",
"    await login(page);",
"    await page.goto(BASE + '/en/recipes');",
"    await page.waitForLoadState('networkidle', { timeout: 15000 });",
"  });",
"  test('9.1 renders heading', async ({ page }) => {",
"    await expect(page.locator('h1').first()).toBeVisible();",
"  });",
"  test('9.2 has create button', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /create/i }).first();",
"    await expect(btn).toBeVisible();",
"  });",
"  test('9.3 create shows form', async ({ page }) => {",
"    await page.locator('button').filter({ hasText: /create/i }).first().click();",
"    await page.waitForTimeout(500);",
"    expect(await page.locator('input[type=\"text\"]').count()).toBeGreaterThan(0);",
"  });",
"  test('9.4 form has category/difficulty selects', async ({ page }) => {",
"    await page.locator('button').filter({ hasText: /create/i }).first().click();",
"    expect(await page.locator('select').count()).toBeGreaterThanOrEqual(2);",
"  });",
"  test('9.5 creates recipe', async ({ page }) => {",
"    await page.locator('button').filter({ hasText: /create/i }).first().click();",
"    await page.waitForTimeout(500);",
"    await page.locator('input[type=\"text\"]').first().fill('E2E Recipe');",
"    await page.locator('button[type=\"submit\"]').first().click();",
"    await page.waitForTimeout(2000);",
"  });",
"  test('9.6 has category tabs', async ({ page }) => {",
"    expect(await page.locator('[role=\"tab\"]').count()).toBeGreaterThanOrEqual(3);",
"  });",
"  test('9.7 switch category', async ({ page }) => {",
"    const tabs = page.locator('[role=\"tab\"]');",
"    if (await tabs.count() > 1) await tabs.nth(1).click();",
"  });",
"});",
"",
"// 10. ANALYTICS PAGE",
"test.describe('10. Analytics', () => {",
"  test.beforeEach(async ({ page }) => {",
"    await login(page);",
"    await page.goto(BASE + '/en/analytics');",
"    await page.waitForLoadState('networkidle', { timeout: 15000 });",
"  });",
"  test('10.1 renders heading', async ({ page }) => {",
"    await expect(page.locator('h1').first()).toBeVisible();",
"  });",
"  test('10.2 has view tabs', async ({ page }) => {",
"    expect(await page.locator('[role=\"tab\"]').count()).toBeGreaterThanOrEqual(2);",
"  });",
"  test('10.3 has buttons for date range', async ({ page }) => {",
"    expect(await page.locator('button').count()).toBeGreaterThan(0);",
"  });",
"});",
"",
"// 11. FASTING PAGE",
"test.describe('11. Fasting', () => {",
"  test.beforeEach(async ({ page }) => {",
"    await login(page);",
"    await page.goto(BASE + '/en/fasting');",
"    await page.waitForLoadState('networkidle', { timeout: 15000 });",
"  });",
"  test('11.1 renders heading', async ({ page }) => {",
"    await expect(page.locator('h1').first()).toBeVisible();",
"  });",
"  test('11.2 has suhoor/iftar time inputs', async ({ page }) => {",
"    expect(await page.locator('input[type=\"time\"]').count()).toBeGreaterThanOrEqual(2);",
"  });",
"  test('11.3 has fasting toggle switches', async ({ page }) => {",
"    expect(await page.locator('[role=\"switch\"]').count()).toBeGreaterThanOrEqual(1);",
"  });",
"  test('11.4 has log completed button', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /completed/i }).first();",
"    await expect(btn).toBeVisible();",
"  });",
"  test('11.5 has log missed button', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /missed/i }).first();",
"    await expect(btn).toBeVisible();",
"  });",
"  test('11.6 toggle switch works', async ({ page }) => {",
"    const sw = page.locator('[role=\"switch\"]').first();",
"    await sw.click();",
"    await page.waitForTimeout(500);",
"  });",
"  test('11.7 log fast completes', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /completed/i }).first();",
"    await btn.click();",
"    await page.waitForTimeout(2000);",
"  });",
"});",
"",
"// 12. NOTIFICATIONS PAGE",
"test.describe('12. Notifications', () => {",
"  test.beforeEach(async ({ page }) => {",
"    await login(page);",
"    await page.goto(BASE + '/en/notifications');",
"    await page.waitForLoadState('networkidle', { timeout: 15000 });",
"  });",
"  test('12.1 renders heading', async ({ page }) => {",
"    await expect(page.locator('h1').first()).toBeVisible();",
"  });",
"  test('12.2 has notification toggle switches', async ({ page }) => {",
"    expect(await page.locator('[role=\"switch\"]').count()).toBeGreaterThanOrEqual(5);",
"  });",
"  test('12.3 toggles a switch', async ({ page }) => {",
"    await page.locator('[role=\"switch\"]').nth(1).click();",
"    await page.waitForTimeout(500);",
"  });",
"});",
"",
"// 13. MEDICAL PAGE",
"test.describe('13. Medical', () => {",
"  test.beforeEach(async ({ page }) => {",
"    await login(page);",
"    await page.goto(BASE + '/en/medical');",
"    await page.waitForLoadState('networkidle', { timeout: 15000 });",
"  });",
"  test('13.1 renders heading', async ({ page }) => {",
"    await expect(page.locator('h1').first()).toBeVisible();",
"  });",
"  test('13.2 has search input', async ({ page }) => {",
"    await expect(page.locator('input').first()).toBeVisible();",
"  });",
"  test('13.3 has nutrient/benefits/considerations tabs', async ({ page }) => {",
"    expect(await page.locator('[role=\"tab\"]').count()).toBeGreaterThanOrEqual(3);",
"  });",
"  test('13.4 entries load from DB', async ({ page }) => {",
"    const body = await page.textContent('body');",
"    expect(body!.length).toBeGreaterThan(100);",
"  });",
"  test('13.5 search filters entries', async ({ page }) => {",
"    await page.locator('input').first().fill('zinc');",
"    await page.waitForTimeout(1000);",
"  });",
"  test('13.6 switch between tabs', async ({ page }) => {",
"    const tabs = page.locator('[role=\"tab\"]');",
"    if (await tabs.count() > 1) {",
"      await tabs.nth(1).click();",
"      await page.waitForTimeout(300);",
"      await tabs.nth(2).click();",
"    }",
"  });",
"});",
"",
"// 14. SETTINGS PAGE",
"test.describe('14. Settings', () => {",
"  test.beforeEach(async ({ page }) => {",
"    await login(page);",
"    await page.goto(BASE + '/en/settings');",
"    await page.waitForLoadState('networkidle', { timeout: 15000 });",
"  });",
"  test('14.1 renders heading', async ({ page }) => {",
"    await expect(page.locator('h1').first()).toBeVisible();",
"  });",
"  test('14.2 has language toggle button', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /English/ }).first();",
"    await expect(btn).toBeVisible();",
"  });",
"  test('14.3 has edit profile button', async ({ page }) => {",
"    const btn = page.locator('button').filter({ hasText: /edit/i }).first();",
"    await expect(btn).toBeVisible();",
"  });",
"  test('14.4 edit shows form with selects', async ({ page }) => {",
"    await page.locator('button').filter({ hasText: /edit/i }).first().click();",
"    await page.waitForTimeout(500);",
"    expect(await page.locator('select').count()).toBeGreaterThanOrEqual(2);",
"  });",
"  test('14.5 cancel edit hides form', async ({ page }) => {",
"    await page.locator('button').filter({ hasText: /edit/i }).first().click();",
"    await page.waitForTimeout(500);",
"    await page.locator('button').filter({ hasText: /cancel/i }).first().click();",
"  });",
"  test('14.6 save profile works', async ({ page }) => {",
"    await page.locator('button').filter({ hasText: /edit/i }).first().click();",
"    await page.waitForTimeout(500);",
"    await page.locator('button').filter({ hasText: /save/i }).first().click();",
"    await page.waitForTimeout(2000);",
"  });",
"});",
"",
"// 15. THEME TOGGLE",
"test.describe('15. Theme', () => {",
"  test('15.1 sidebar has theme area', async ({ page }) => {",
"    await login(page);",
"    await page.waitForTimeout(1000);",
"    await expect(page.locator('aside')).toBeVisible();",
"  });",
"  test('15.2 toggle changes html class', async ({ page }) => {",
"    await login(page);",
"    await page.waitForTimeout(1000);",
"    const before = await page.locator('html').getAttribute('class');",
"    const btn = page.locator('aside button').last();",
"    if (await btn.isVisible()) {",
"      await btn.click();",
"      await page.waitForTimeout(1000);",
"      const after = await page.locator('html').getAttribute('class');",
"      expect(before).not.toBe(after);",
"    }",
"  });",
"});",
"",
"// 16. ARABIC LOCALE",
"test.describe('16. Arabic Locale', () => {",
"  const arRoutes = ['dashboard','meals','body','fasting','settings','recipes','medical','notifications','analytics'];",
"  for (const r of arRoutes) {",
"    test('16.x /ar/' + r + ' renders', async ({ page }) => {",
"      await login(page);",
"      await page.goto(BASE + '/ar/' + r);",
"      await page.waitForLoadState('networkidle', { timeout: 15000 });",
"      expect(page.url()).toContain('/ar/' + r);",
"    });",
"  }",
"});",
"",
"// 17. API SMOKE TESTS",
"test.describe('17. API Endpoints', () => {",
"  test('17.1 foods API returns data', async ({ request }) => {",
"    const res = await request.get(BASE + '/api/foods?q=rice');",
"    expect(res.ok()).toBeTruthy();",
"    const data = await res.json();",
"    expect(data).toHaveProperty('foods');",
"  });",
"  test('17.2 medical API returns data', async ({ request }) => {",
"    const res = await request.get(BASE + '/api/medical');",
"    expect(res.ok()).toBeTruthy();",
"  });",
"  test('17.3 recipes API returns data', async ({ request }) => {",
"    const res = await request.get(BASE + '/api/recipes');",
"    expect(res.ok()).toBeTruthy();",
"  });",
"  test('17.4 dashboard requires auth', async ({ request }) => {",
"    const res = await request.get(BASE + '/api/dashboard');",
"    expect(res.status()).toBe(401);",
"  });",
"  test('17.5 foods requires auth', async ({ request }) => {",
"    const res = await request.get(BASE + '/api/foods');",
"    expect(res.status()).toBe(401);",
"  });",
"  test('17.6 register works', async ({ request }) => {",
"    const res = await request.post(BASE + '/api/auth/register', {",
"      data: { name: 'API Test', email: 'api_' + Date.now() + '@test.com', password: 'ApiTest123!' },",
"    });",
"    expect(res.ok()).toBeTruthy();",
"  });",
"  test('17.7 register rejects short password', async ({ request }) => {",
"    const res = await request.post(BASE + '/api/auth/register', {",
"      data: { name: 'Short', email: 'short_' + Date.now() + '@test.com', password: 'abc' },",
"    });",
"    expect(res.status()).toBe(400);",
"  });",
"  test('17.8 register rejects bad email', async ({ request }) => {",
"    const res = await request.post(BASE + '/api/auth/register', {",
"      data: { name: 'Bad', email: 'notanemail', password: 'Test12345!' },",
"    });",
"    expect(res.status()).toBe(400);",
"  });",
"});",
"",
"// 18. 404 PAGE",
"test('18.1 404 renders for nonexistent route', async ({ page }) => {",
"  await page.goto(BASE + '/en/nonexistent-page-xyz');",
"  await page.waitForTimeout(2000);",
"  const body = await page.textContent('body');",
"  expect(body).toBeTruthy();",
"});",
].join('\n');

fs.writeFileSync(path.join(__dirname, 'app.spec.ts'), code);
console.log('Written ' + code.length + ' chars to e2e/app.spec.ts');
