import "dotenv/config";
import mongoose from "mongoose";

const MONGODB_URI = process.env.MONGODB_URI!;

const foodSchema = new mongoose.Schema(
  {
    source: { type: String, default: "usda" },
    name: { type: String, required: true },
    nameAr: String,
    brand: String,
    category: { type: String, required: true },
    servingSize: { type: Number, default: 100 },
    servingUnit: { type: String, default: "g" },
    servingDescription: String,
    nutrientProfile: mongoose.Schema.Types.Mixed,
    dataQuality: { type: String, default: "verified" },
    region: { type: String, default: "egypt" },
  },
  { timestamps: true, collection: "foods" }
);

const Food = mongoose.model("Food", foodSchema);

const foods = [
  {
    name: "Koshari",
    nameAr: "كشري",
    category: "grains",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 plate",
    nutrientProfile: {
      calories: 237,
      protein: 8.2,
      carbs: 42.5,
      fat: 3.8,
      fiber: 4.2,
      sugar: 3.1,
      sodium: 480,
      saturatedFat: 0.8,
      cholesterol: 0,
      vitaminA: 8,
      vitaminC: 6,
      calcium: 45,
      iron: 2.8,
    },
  },
  {
    name: "Ful Medames",
    nameAr: "فول مدمس",
    category: "protein",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 198,
      protein: 12.4,
      carbs: 30.2,
      fat: 2.8,
      fiber: 8.6,
      sugar: 1.2,
      sodium: 320,
      saturatedFat: 0.4,
      cholesterol: 0,
      vitaminA: 4,
      vitaminC: 8,
      calcium: 72,
      iron: 4.2,
    },
  },
  {
    name: "Taameya (Falafel)",
    nameAr: "طعمية",
    category: "protein",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "4-5 pieces",
    nutrientProfile: {
      calories: 254,
      protein: 11.8,
      carbs: 28.4,
      fat: 11.2,
      fiber: 5.8,
      sugar: 1.5,
      sodium: 410,
      saturatedFat: 1.4,
      cholesterol: 0,
      vitaminA: 6,
      vitaminC: 4,
      calcium: 98,
      iron: 3.6,
    },
  },
  {
    name: "Molokhia",
    nameAr: "ملوخية",
    category: "vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl with rice",
    nutrientProfile: {
      calories: 45,
      protein: 3.2,
      carbs: 6.8,
      fat: 0.4,
      fiber: 3.1,
      sugar: 0.8,
      sodium: 28,
      saturatedFat: 0.1,
      cholesterol: 0,
      vitaminA: 8500,
      vitaminC: 32,
      calcium: 152,
      iron: 6.4,
    },
  },
  {
    name: "Fattah",
    nameAr: "فتة",
    category: "grains",
    servingSize: 300,
    servingUnit: "g",
    servingDescription: "1 plate",
    nutrientProfile: {
      calories: 285,
      protein: 18.5,
      carbs: 32.4,
      fat: 8.6,
      fiber: 2.1,
      sugar: 2.8,
      sodium: 520,
      saturatedFat: 3.2,
      cholesterol: 45,
      vitaminA: 12,
      vitaminC: 4,
      calcium: 180,
      iron: 2.4,
    },
  },
  {
    name: "Kawareh",
    nameAr: "كوارع",
    category: "protein",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 serving",
    nutrientProfile: {
      calories: 320,
      protein: 28.4,
      carbs: 4.2,
      fat: 21.6,
      fiber: 0.3,
      sugar: 0.8,
      sodium: 680,
      saturatedFat: 8.4,
      cholesterol: 95,
      vitaminA: 0,
      vitaminC: 2,
      calcium: 42,
      iron: 3.2,
    },
  },
  {
    name: "Shawarma (Chicken)",
    nameAr: "شاورما فراخ",
    category: "protein",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 sandwich",
    nutrientProfile: {
      calories: 380,
      protein: 24.5,
      carbs: 32.8,
      fat: 16.4,
      fiber: 1.8,
      sugar: 3.2,
      sodium: 720,
      saturatedFat: 4.2,
      cholesterol: 72,
      vitaminA: 15,
      vitaminC: 8,
      calcium: 120,
      iron: 2.1,
    },
  },
  {
    name: "Hawawshi",
    nameAr: "حواوشي",
    category: "protein",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 sandwich",
    nutrientProfile: {
      calories: 420,
      protein: 22.8,
      carbs: 38.4,
      fat: 19.2,
      fiber: 2.4,
      sugar: 4.1,
      sodium: 650,
      saturatedFat: 6.8,
      cholesterol: 55,
      vitaminA: 22,
      vitaminC: 12,
      calcium: 85,
      iron: 3.4,
    },
  },
  {
    name: "Warak Enab",
    nameAr: "ورق عنب",
    category: "vegetables",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "8-10 pieces",
    nutrientProfile: {
      calories: 135,
      protein: 3.8,
      carbs: 18.2,
      fat: 5.4,
      fiber: 4.8,
      sugar: 2.4,
      sodium: 380,
      saturatedFat: 1.2,
      cholesterol: 0,
      vitaminA: 45,
      vitaminC: 14,
      calcium: 68,
      iron: 2.2,
    },
  },
  {
    name: "Om Ali",
    nameAr: "أم علي",
    category: "desserts",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 320,
      protein: 8.4,
      carbs: 38.6,
      fat: 14.8,
      fiber: 1.2,
      sugar: 22.4,
      sodium: 180,
      saturatedFat: 6.8,
      cholesterol: 28,
      vitaminA: 8,
      vitaminC: 2,
      calcium: 165,
      iron: 1.4,
    },
  },
  {
    name: "Roz Bel Laban",
    nameAr: "رز باللبن",
    category: "grains",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 195,
      protein: 5.8,
      carbs: 32.4,
      fat: 4.8,
      fiber: 0.8,
      sugar: 14.2,
      sodium: 95,
      saturatedFat: 2.8,
      cholesterol: 12,
      vitaminA: 4,
      vitaminC: 0,
      calcium: 125,
      iron: 1.2,
    },
  },
  {
    name: "Kunafa",
    nameAr: "كنافة",
    category: "desserts",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "1 piece",
    nutrientProfile: {
      calories: 385,
      protein: 6.8,
      carbs: 42.4,
      fat: 21.6,
      fiber: 0.8,
      sugar: 24.8,
      sodium: 220,
      saturatedFat: 8.4,
      cholesterol: 35,
      vitaminA: 6,
      vitaminC: 0,
      calcium: 142,
      iron: 1.6,
    },
  },
  {
    name: "Feseekh",
    nameAr: "فسيخ",
    category: "protein",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "1 serving",
    nutrientProfile: {
      calories: 156,
      protein: 24.8,
      carbs: 0,
      fat: 6.2,
      fiber: 0,
      sugar: 0,
      sodium: 1240,
      saturatedFat: 1.4,
      cholesterol: 52,
      vitaminA: 2,
      vitaminC: 0,
      calcium: 28,
      iron: 1.8,
    },
  },
  {
    name: "Sayyadiah",
    nameAr: "سمك سيادية",
    category: "protein",
    servingSize: 300,
    servingUnit: "g",
    servingDescription: "1 plate",
    nutrientProfile: {
      calories: 345,
      protein: 28.4,
      carbs: 35.2,
      fat: 8.6,
      fiber: 1.4,
      sugar: 1.2,
      sodium: 580,
      saturatedFat: 1.8,
      cholesterol: 55,
      vitaminA: 6,
      vitaminC: 4,
      calcium: 45,
      iron: 2.2,
    },
  },
  {
    name: "Bamia",
    nameAr: "بامية",
    category: "vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 85,
      protein: 4.2,
      carbs: 12.8,
      fat: 2.1,
      fiber: 5.4,
      sugar: 3.2,
      sodium: 320,
      saturatedFat: 0.4,
      cholesterol: 8,
      vitaminA: 32,
      vitaminC: 18,
      calcium: 82,
      iron: 2.4,
    },
  },
  {
    name: "Mahshi (Grape Leaves)",
    nameAr: "محشي ورق عنب",
    category: "vegetables",
    servingSize: 180,
    servingUnit: "g",
    servingDescription: "10-12 pieces",
    nutrientProfile: {
      calories: 165,
      protein: 4.8,
      carbs: 22.4,
      fat: 6.2,
      fiber: 5.2,
      sugar: 2.8,
      sodium: 420,
      saturatedFat: 1.4,
      cholesterol: 0,
      vitaminA: 38,
      vitaminC: 12,
      calcium: 78,
      iron: 2.8,
    },
  },
  {
    name: "Falafel Sandwich",
    nameAr: "ساندويتش فلافل",
    category: "protein",
    servingSize: 220,
    servingUnit: "g",
    servingDescription: "1 sandwich",
    nutrientProfile: {
      calories: 340,
      protein: 12.8,
      carbs: 42.4,
      fat: 13.2,
      fiber: 6.8,
      sugar: 4.2,
      sodium: 620,
      saturatedFat: 1.8,
      cholesterol: 0,
      vitaminA: 8,
      vitaminC: 14,
      calcium: 112,
      iron: 4.2,
    },
  },
  {
    name: "French Fries",
    nameAr: "بطاطس محمرة",
    category: "sides",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "1 medium portion",
    nutrientProfile: {
      calories: 312,
      protein: 3.4,
      carbs: 41.4,
      fat: 14.8,
      fiber: 3.8,
      sugar: 0.4,
      sodium: 210,
      saturatedFat: 2.8,
      cholesterol: 0,
      vitaminA: 0,
      vitaminC: 12,
      calcium: 14,
      iron: 1.2,
    },
  },
  {
    name: "Aish Baladi",
    nameAr: "عيش بلدي",
    category: "grains",
    servingSize: 60,
    servingUnit: "g",
    servingDescription: "1 loaf",
    nutrientProfile: {
      calories: 168,
      protein: 5.4,
      carbs: 32.8,
      fat: 1.2,
      fiber: 2.4,
      sugar: 1.2,
      sodium: 340,
      saturatedFat: 0.2,
      cholesterol: 0,
      vitaminA: 0,
      vitaminC: 0,
      calcium: 18,
      iron: 1.8,
    },
  },
  {
    name: "Mahalabia",
    nameAr: "مهلبية",
    category: "desserts",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "1 cup",
    nutrientProfile: {
      calories: 145,
      protein: 4.8,
      carbs: 18.2,
      fat: 6.1,
      fiber: 0,
      sugar: 15.4,
      sodium: 85,
      saturatedFat: 3.8,
      cholesterol: 18,
      vitaminA: 4,
      vitaminC: 0,
      calcium: 148,
      iron: 0.4,
    },
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");

    await Food.deleteMany({});
    console.log("Cleared existing foods");

    await Food.insertMany(foods);
    console.log(`Seeded ${foods.length} Egyptian foods`);

    await mongoose.disconnect();
    console.log("Done!");
  } catch (error) {
    console.error("Seed error:", error);
    process.exit(1);
  }
}

seed();
