import "dotenv/config";
import mongoose from "mongoose";

const MONGODB_URI = process.env.MONGODB_URI!;

const foodSchema = new mongoose.Schema(
  {
    source: { type: String, default: "usda" },
    name: { type: String, required: true },
    nameAr: String,
    brand: String,
    category: { type: String, required: true },
    servingSize: { type: Number, default: 100 },
    servingUnit: { type: String, default: "g" },
    servingDescription: String,
    nutrientProfile: mongoose.Schema.Types.Mixed,
    dataQuality: { type: String, default: "verified" },
    region: { type: String, default: "egypt" },
  },
  { timestamps: true, collection: "foods" }
);

const Food = mongoose.model("Food", foodSchema);

const foods = [
  {
    name: "Koshari",
    nameAr: "كشري",
    category: "grains",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 plate",
    nutrientProfile: {
      calories: 237,
      protein: 8.2,
      carbs: 42.5,
      fat: 3.8,
      fiber: 4.2,
      sugar: 3.1,
      sodium: 480,
      saturatedFat: 0.8,
      cholesterol: 0,
      vitaminA: 8,
      vitaminC: 6,
      calcium: 45,
      iron: 2.8,
    },
  },
  {
    name: "Ful Medames",
    nameAr: "فول مدمس",
    category: "protein",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 198,
      protein: 12.4,
      carbs: 30.2,
      fat: 2.8,
      fiber: 8.6,
      sugar: 1.2,
      sodium: 320,
      saturatedFat: 0.4,
      cholesterol: 0,
      vitaminA: 4,
      vitaminC: 8,
      calcium: 72,
      iron: 4.2,
    },
  },
  {
    name: "Taameya (Falafel)",
    nameAr: "طعمية",
    category: "protein",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "4-5 pieces",
    nutrientProfile: {
      calories: 254,
      protein: 11.8,
      carbs: 28.4,
      fat: 11.2,
      fiber: 5.8,
      sugar: 1.5,
      sodium: 410,
      saturatedFat: 1.4,
      cholesterol: 0,
      vitaminA: 6,
      vitaminC: 4,
      calcium: 98,
      iron: 3.6,
    },
  },
  {
    name: "Molokhia",
    nameAr: "ملوخية",
    category: "vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl with rice",
    nutrientProfile: {
      calories: 45,
      protein: 3.2,
      carbs: 6.8,
      fat: 0.4,
      fiber: 3.1,
      sugar: 0.8,
      sodium: 28,
      saturatedFat: 0.1,
      cholesterol: 0,
      vitaminA: 8500,
      vitaminC: 32,
      calcium: 152,
      iron: 6.4,
    },
  },
  {
    name: "Fattah",
    nameAr: "فتة",
    category: "grains",
    servingSize: 300,
    servingUnit: "g",
    servingDescription: "1 plate",
    nutrientProfile: {
      calories: 285,
      protein: 18.5,
      carbs: 32.4,
      fat: 8.6,
      fiber: 2.1,
      sugar: 2.8,
      sodium: 520,
      saturatedFat: 3.2,
      cholesterol: 45,
      vitaminA: 12,
      vitaminC: 4,
      calcium: 180,
      iron: 2.4,
    },
  },
  {
    name: "Kawareh",
    nameAr: "كوارع",
    category: "protein",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 serving",
    nutrientProfile: {
      calories: 320,
      protein: 28.4,
      carbs: 4.2,
      fat: 21.6,
      fiber: 0.3,
      sugar: 0.8,
      sodium: 680,
      saturatedFat: 8.4,
      cholesterol: 95,
      vitaminA: 0,
      vitaminC: 2,
      calcium: 42,
      iron: 3.2,
    },
  },
  {
    name: "Shawarma (Chicken)",
    nameAr: "شاورما فراخ",
    category: "protein",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 sandwich",
    nutrientProfile: {
      calories: 380,
      protein: 24.5,
      carbs: 32.8,
      fat: 16.4,
      fiber: 1.8,
      sugar: 3.2,
      sodium: 720,
      saturatedFat: 4.2,
      cholesterol: 72,
      vitaminA: 15,
      vitaminC: 8,
      calcium: 120,
      iron: 2.1,
    },
  },
  {
    name: "Hawawshi",
    nameAr: "حواوشي",
    category: "protein",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 sandwich",
    nutrientProfile: {
      calories: 420,
      protein: 22.8,
      carbs: 38.4,
      fat: 19.2,
      fiber: 2.4,
      sugar: 4.1,
      sodium: 650,
      saturatedFat: 6.8,
      cholesterol: 55,
      vitaminA: 22,
      vitaminC: 12,
      calcium: 85,
      iron: 3.4,
    },
  },
  {
    name: "Warak Enab",
    nameAr: "ورق عنب",
    category: "vegetables",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "8-10 pieces",
    nutrientProfile: {
      calories: 135,
      protein: 3.8,
      carbs: 18.2,
      fat: 5.4,
      fiber: 4.8,
      sugar: 2.4,
      sodium: 380,
      saturatedFat: 1.2,
      cholesterol: 0,
      vitaminA: 45,
      vitaminC: 14,
      calcium: 68,
      iron: 2.2,
    },
  },
  {
    name: "Om Ali",
    nameAr: "أم علي",
    category: "desserts",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 320,
      protein: 8.4,
      carbs: 38.6,
      fat: 14.8,
      fiber: 1.2,
      sugar: 22.4,
      sodium: 180,
      saturatedFat: 6.8,
      cholesterol: 28,
      vitaminA: 8,
      vitaminC: 2,
      calcium: 165,
      iron: 1.4,
    },
  },
  {
    name: "Roz Bel Laban",
    nameAr: "رز باللبن",
    category: "grains",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 195,
      protein: 5.8,
      carbs: 32.4,
      fat: 4.8,
      fiber: 0.8,
      sugar: 14.2,
      sodium: 95,
      saturatedFat: 2.8,
      cholesterol: 12,
      vitaminA: 4,
      vitaminC: 0,
      calcium: 125,
      iron: 1.2,
    },
  },
  {
    name: "Kunafa",
    nameAr: "كنافة",
    category: "desserts",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "1 piece",
    nutrientProfile: {
      calories: 385,
      protein: 6.8,
      carbs: 42.4,
      fat: 21.6,
      fiber: 0.8,
      sugar: 24.8,
      sodium: 220,
      saturatedFat: 8.4,
      cholesterol: 35,
      vitaminA: 6,
      vitaminC: 0,
      calcium: 142,
      iron: 1.6,
    },
  },
  {
    name: "Feseekh",
    nameAr: "فسيخ",
    category: "protein",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "1 serving",
    nutrientProfile: {
      calories: 156,
      protein: 24.8,
      carbs: 0,
      fat: 6.2,
      fiber: 0,
      sugar: 0,
      sodium: 1240,
      saturatedFat: 1.4,
      cholesterol: 52,
      vitaminA: 2,
      vitaminC: 0,
      calcium: 28,
      iron: 1.8,
    },
  },
  {
    name: "Sayyadiah",
    nameAr: "سمك سيادية",
    category: "protein",
    servingSize: 300,
    servingUnit: "g",
    servingDescription: "1 plate",
    nutrientProfile: {
      calories: 345,
      protein: 28.4,
      carbs: 35.2,
      fat: 8.6,
      fiber: 1.4,
      sugar: 1.2,
      sodium: 580,
      saturatedFat: 1.8,
      cholesterol: 55,
      vitaminA: 6,
      vitaminC: 4,
      calcium: 45,
      iron: 2.2,
    },
  },
  {
    name: "Bamia",
    nameAr: "بامية",
    category: "vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 85,
      protein: 4.2,
      carbs: 12.8,
      fat: 2.1,
      fiber: 5.4,
      sugar: 3.2,
      sodium: 320,
      saturatedFat: 0.4,
      cholesterol: 8,
      vitaminA: 32,
      vitaminC: 18,
      calcium: 82,
      iron: 2.4,
    },
  },
  {
    name: "Mahshi (Grape Leaves)",
    nameAr: "محشي ورق عنب",
    category: "vegetables",
    servingSize: 180,
    servingUnit: "g",
    servingDescription: "10-12 pieces",
    nutrientProfile: {
      calories: 165,
      protein: 4.8,
      carbs: 22.4,
      fat: 6.2,
      fiber: 5.2,
      sugar: 2.8,
      sodium: 420,
      saturatedFat: 1.4,
      cholesterol: 0,
      vitaminA: 38,
      vitaminC: 12,
      calcium: 78,
      iron: 2.8,
    },
  },
  {
    name: "Falafel Sandwich",
    nameAr: "ساندويتش فلافل",
    category: "protein",
    servingSize: 220,
    servingUnit: "g",
    servingDescription: "1 sandwich",
    nutrientProfile: {
      calories: 340,
      protein: 12.8,
      carbs: 42.4,
      fat: 13.2,
      fiber: 6.8,
      sugar: 4.2,
      sodium: 620,
      saturatedFat: 1.8,
      cholesterol: 0,
      vitaminA: 8,
      vitaminC: 14,
      calcium: 112,
      iron: 4.2,
    },
  },
  {
    name: "French Fries",
    nameAr: "بطاطس محمرة",
    category: "sides",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "1 medium portion",
    nutrientProfile: {
      calories: 312,
      protein: 3.4,
      carbs: 41.4,
      fat: 14.8,
      fiber: 3.8,
      sugar: 0.4,
      sodium: 210,
      saturatedFat: 2.8,
      cholesterol: 0,
      vitaminA: 0,
      vitaminC: 12,
      calcium: 14,
      iron: 1.2,
    },
  },
  {
    name: "Aish Baladi",
    nameAr: "عيش بلدي",
    category: "grains",
    servingSize: 60,
    servingUnit: "g",
    servingDescription: "1 loaf",
    nutrientProfile: {
      calories: 168,
      protein: 5.4,
      carbs: 32.8,
      fat: 1.2,
      fiber: 2.4,
      sugar: 1.2,
      sodium: 340,
      saturatedFat: 0.2,
      cholesterol: 0,
      vitaminA: 0,
      vitaminC: 0,
      calcium: 18,
      iron: 1.8,
    },
  },
  {
    name: "Mahalabia",
    nameAr: "مهلبية",
    category: "desserts",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "1 cup",
    nutrientProfile: {
      calories: 145,
      protein: 4.8,
      carbs: 18.2,
      fat: 6.1,
      fiber: 0,
      sugar: 15.4,
      sodium: 85,
      saturatedFat: 3.8,
      cholesterol: 18,
      vitaminA: 4,
      vitaminC: 0,
      calcium: 148,
      iron: 0.4,
    },
  },
  {
    name: "Fatta Beaf",
    nameAr: "فتة لحم",
    category: "protein",
    servingSize: 350,
    servingUnit: "g",
    servingDescription: "1 plate",
    nutrientProfile: {
      calories: 340,
      protein: 24.8,
      carbs: 30.5,
      fat: 12.2,
      fiber: 1.8,
      sugar: 3.2,
      sodium: 580,
      saturatedFat: 4.8,
      cholesterol: 68,
      vitaminA: 15,
      vitaminC: 6,
      calcium: 210,
      iron: 3.4,
    },
  },
  {
    name: "Sayyadieh (Fish)",
    nameAr: "سمك سيادية",
    category: "protein",
    servingSize: 350,
    servingUnit: "g",
    servingDescription: "1 plate with rice",
    nutrientProfile: {
      calories: 380,
      protein: 30.2,
      carbs: 38.5,
      fat: 9.8,
      fiber: 1.6,
      sugar: 1.4,
      sodium: 620,
      saturatedFat: 2.1,
      cholesterol: 62,
      vitaminA: 8,
      vitaminC: 5,
      calcium: 52,
      iron: 2.8,
    },
  },
  {
    name: "Liver (Kibda)",
    nameAr: "كبدة",
    category: "protein",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "1 sandwich or plate",
    nutrientProfile: {
      calories: 265,
      protein: 21.8,
      carbs: 8.4,
      fat: 15.6,
      fiber: 1.2,
      sugar: 2.8,
      sodium: 420,
      saturatedFat: 5.2,
      cholesterol: 285,
      vitaminA: 12400,
      vitaminC: 14,
      calcium: 22,
      iron: 6.8,
    },
  },
  {
    name: "Grilled Kofta",
    nameAr: "كفتة مشوية",
    category: "protein",
    servingSize: 180,
    servingUnit: "g",
    servingDescription: "4-5 pieces",
    nutrientProfile: {
      calories: 340,
      protein: 26.4,
      carbs: 4.2,
      fat: 24.8,
      fiber: 0.6,
      sugar: 1.2,
      sodium: 480,
      saturatedFat: 9.6,
      cholesterol: 95,
      vitaminA: 6,
      vitaminC: 2,
      calcium: 28,
      iron: 3.2,
    },
  },
  {
    name: "Shawarma (Beef)",
    nameAr: "شاورما لحم",
    category: "protein",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 sandwich",
    nutrientProfile: {
      calories: 410,
      protein: 22.8,
      carbs: 33.4,
      fat: 21.2,
      fiber: 2.1,
      sugar: 3.8,
      sodium: 680,
      saturatedFat: 8.4,
      cholesterol: 78,
      vitaminA: 18,
      vitaminC: 10,
      calcium: 110,
      iron: 2.8,
    },
  },
  {
    name: "Feteer Meshaltet",
    nameAr: "فطير مشلتت",
    category: "grains",
    servingSize: 120,
    servingUnit: "g",
    servingDescription: "1 piece",
    nutrientProfile: {
      calories: 360,
      protein: 6.8,
      carbs: 42.5,
      fat: 18.6,
      fiber: 1.4,
      sugar: 2.4,
      sodium: 380,
      saturatedFat: 8.2,
      cholesterol: 30,
      vitaminA: 6,
      vitaminC: 0,
      calcium: 35,
      iron: 2.4,
    },
  },
  {
    name: "Basbousa",
    nameAr: "بسبوسة",
    category: "desserts",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "1 piece",
    nutrientProfile: {
      calories: 340,
      protein: 4.2,
      carbs: 52.8,
      fat: 13.4,
      fiber: 0.8,
      sugar: 28.6,
      sodium: 120,
      saturatedFat: 6.2,
      cholesterol: 22,
      vitaminA: 4,
      vitaminC: 0,
      calcium: 45,
      iron: 1.8,
    },
  },
  {
    name: "Qatayef (Nut-filled)",
    nameAr: "قطايف بالمكسرات",
    category: "desserts",
    servingSize: 120,
    servingUnit: "g",
    servingDescription: "3 pieces",
    nutrientProfile: {
      calories: 310,
      protein: 6.4,
      carbs: 38.2,
      fat: 15.8,
      fiber: 2.1,
      sugar: 16.4,
      sodium: 95,
      saturatedFat: 3.4,
      cholesterol: 8,
      vitaminA: 2,
      vitaminC: 0,
      calcium: 52,
      iron: 2.2,
    },
  },
  {
    name: "Mahshi (Zucchini)",
    nameAr: "كوسة محشي",
    category: "vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "4-5 pieces",
    nutrientProfile: {
      calories: 145,
      protein: 6.8,
      carbs: 14.2,
      fat: 7.2,
      fiber: 3.4,
      sugar: 4.8,
      sodium: 380,
      saturatedFat: 2.2,
      cholesterol: 18,
      vitaminA: 28,
      vitaminC: 22,
      calcium: 68,
      iron: 2.1,
    },
  },
  {
    name: "Mahshi (Cabbage)",
    nameAr: "كرنب محشي",
    category: "vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "4-5 pieces",
    nutrientProfile: {
      calories: 135,
      protein: 6.2,
      carbs: 12.8,
      fat: 7.4,
      fiber: 3.8,
      sugar: 5.2,
      sodium: 400,
      saturatedFat: 2.4,
      cholesterol: 18,
      vitaminA: 22,
      vitaminC: 28,
      calcium: 72,
      iron: 1.8,
    },
  },
  {
    name: "Mahshi (Eggplant)",
    nameAr: "باذنجان محشي",
    category: "vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "3-4 pieces",
    nutrientProfile: {
      calories: 155,
      protein: 5.8,
      carbs: 15.4,
      fat: 8.2,
      fiber: 4.2,
      sugar: 5.8,
      sodium: 360,
      saturatedFat: 2.6,
      cholesterol: 18,
      vitaminA: 18,
      vitaminC: 16,
      calcium: 58,
      iron: 1.6,
    },
  },
  {
    name: "Shakshuka",
    nameAr: "شكشوكة",
    category: "protein",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 serving with bread",
    nutrientProfile: {
      calories: 220,
      protein: 12.8,
      carbs: 14.2,
      fat: 13.6,
      fiber: 3.8,
      sugar: 8.4,
      sodium: 480,
      saturatedFat: 3.8,
      cholesterol: 186,
      vitaminA: 42,
      vitaminC: 28,
      calcium: 95,
      iron: 3.2,
    },
  },
  {
    name: "Baba Ghanoush",
    nameAr: "بابا غنوج",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "4 tbsp",
    nutrientProfile: {
      calories: 115,
      protein: 2.4,
      carbs: 8.6,
      fat: 8.8,
      fiber: 3.2,
      sugar: 4.2,
      sodium: 320,
      saturatedFat: 1.2,
      cholesterol: 0,
      vitaminA: 8,
      vitaminC: 12,
      calcium: 38,
      iron: 1.1,
    },
  },
  {
    name: "Tahini Salad",
    nameAr: "سلطة طحينة",
    category: "vegetables",
    servingSize: 120,
    servingUnit: "g",
    servingDescription: "4 tbsp",
    nutrientProfile: {
      calories: 165,
      protein: 4.8,
      carbs: 8.2,
      fat: 13.4,
      fiber: 1.8,
      sugar: 1.2,
      sodium: 280,
      saturatedFat: 1.8,
      cholesterol: 0,
      vitaminA: 4,
      vitaminC: 6,
      calcium: 68,
      iron: 2.4,
    },
  },
  {
    name: "Fattet Hummus",
    nameAr: "فتة حمص",
    category: "grains",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 245,
      protein: 10.2,
      carbs: 28.4,
      fat: 10.8,
      fiber: 5.2,
      sugar: 2.8,
      sodium: 440,
      saturatedFat: 2.4,
      cholesterol: 5,
      vitaminA: 6,
      vitaminC: 4,
      calcium: 88,
      iron: 3.4,
    },
  },
  {
    name: "Hummus",
    nameAr: "حمص",
    category: "protein",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "4 tbsp",
    nutrientProfile: {
      calories: 170,
      protein: 7.8,
      carbs: 14.2,
      fat: 10.4,
      fiber: 4.8,
      sugar: 0.8,
      sodium: 380,
      saturatedFat: 1.4,
      cholesterol: 0,
      vitaminA: 2,
      vitaminC: 4,
      calcium: 42,
      iron: 2.8,
    },
  },
  {
    name: "Bessara",
    nameAr: "بصارة",
    category: "vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 125,
      protein: 8.4,
      carbs: 12.8,
      fat: 4.8,
      fiber: 6.2,
      sugar: 1.4,
      sodium: 340,
      saturatedFat: 0.8,
      cholesterol: 0,
      vitaminA: 18,
      vitaminC: 12,
      calcium: 82,
      iron: 4.8,
    },
  },
  {
    name: "Sabanekh bil Zeit",
    nameAr: "سبانخ بالزيت",
    category: "vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 145,
      protein: 6.8,
      carbs: 8.4,
      fat: 10.2,
      fiber: 4.2,
      sugar: 1.8,
      sodium: 380,
      saturatedFat: 1.4,
      cholesterol: 0,
      vitaminA: 9200,
      vitaminC: 24,
      calcium: 185,
      iron: 5.8,
    },
  },
  {
    name: "Besara bil Feel",
    nameAr: "بصارة بالفيل",
    category: "protein",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 bowl with bread",
    nutrientProfile: {
      calories: 195,
      protein: 12.8,
      carbs: 14.2,
      fat: 10.4,
      fiber: 6.8,
      sugar: 2.2,
      sodium: 360,
      saturatedFat: 1.8,
      cholesterol: 0,
      vitaminA: 22,
      vitaminC: 14,
      calcium: 95,
      iron: 5.4,
    },
  },
  {
    name: "Roz bel Laban bil Mango",
    nameAr: "رز باللبن بالمانجو",
    category: "desserts",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 225,
      protein: 5.4,
      carbs: 42.8,
      fat: 4.6,
      fiber: 1.4,
      sugar: 24.6,
      sodium: 88,
      saturatedFat: 2.6,
      cholesterol: 10,
      vitaminA: 32,
      vitaminC: 18,
      calcium: 118,
      iron: 1.0,
    },
  },
  {
    name: "Konafa bil Qishtah",
    nameAr: "كنافة بالقشطة",
    category: "desserts",
    servingSize: 180,
    servingUnit: "g",
    servingDescription: "1 piece",
    nutrientProfile: {
      calories: 420,
      protein: 7.4,
      carbs: 45.8,
      fat: 24.2,
      fiber: 0.6,
      sugar: 28.4,
      sodium: 240,
      saturatedFat: 10.2,
      cholesterol: 42,
      vitaminA: 8,
      vitaminC: 0,
      calcium: 165,
      iron: 1.8,
    },
  },
  {
    name: "Baked Potato with Bechamel",
    nameAr: "بطاطس بالبشاميل",
    category: "sides",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 serving",
    nutrientProfile: {
      calories: 310,
      protein: 12.8,
      carbs: 28.4,
      fat: 17.2,
      fiber: 2.8,
      sugar: 2.4,
      sodium: 520,
      saturatedFat: 7.8,
      cholesterol: 55,
      vitaminA: 12,
      vitaminC: 18,
      calcium: 185,
      iron: 1.8,
    },
  },
  {
    name: "Béchamel Pasta",
    nameAr: "مكرونة بالبشاميل",
    category: "grains",
    servingSize: 300,
    servingUnit: "g",
    servingDescription: "1 plate",
    nutrientProfile: {
      calories: 380,
      protein: 18.4,
      carbs: 35.2,
      fat: 19.8,
      fiber: 2.2,
      sugar: 3.4,
      sodium: 560,
      saturatedFat: 8.6,
      cholesterol: 68,
      vitaminA: 14,
      vitaminC: 6,
      calcium: 220,
      iron: 2.4,
    },
  },
  {
    name: "Roz bel Reeha",
    nameAr: "رز بالريحة",
    category: "grains",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "1 plate",
    nutrientProfile: {
      calories: 215,
      protein: 4.2,
      carbs: 42.8,
      fat: 3.4,
      fiber: 0.6,
      sugar: 0,
      sodium: 180,
      saturatedFat: 0.8,
      cholesterol: 0,
      vitaminA: 0,
      vitaminC: 0,
      calcium: 12,
      iron: 1.4,
    },
  },
  {
    name: "Roz bil Zabadi",
    nameAr: "رز بالزبادي",
    category: "grains",
    servingSize: 250,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 165,
      protein: 6.8,
      carbs: 28.4,
      fat: 3.2,
      fiber: 0.4,
      sugar: 6.8,
      sodium: 120,
      saturatedFat: 1.8,
      cholesterol: 8,
      vitaminA: 2,
      vitaminC: 0,
      calcium: 85,
      iron: 1.0,
    },
  },
  {
    name: "Waraq Enab bil Zeit",
    nameAr: "ورق عنب بالزيت",
    category: "vegetables",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "8-10 pieces",
    nutrientProfile: {
      calories: 155,
      protein: 3.4,
      carbs: 16.8,
      fat: 8.4,
      fiber: 4.2,
      sugar: 3.8,
      sodium: 340,
      saturatedFat: 1.2,
      cholesterol: 0,
      vitaminA: 42,
      vitaminC: 14,
      calcium: 62,
      iron: 2.0,
    },
  },
  {
    name: "Kushari bil Shatta",
    nameAr: "كشري بالشطة",
    category: "grains",
    servingSize: 300,
    servingUnit: "g",
    servingDescription: "1 large plate",
    nutrientProfile: {
      calories: 275,
      protein: 9.4,
      carbs: 48.2,
      fat: 4.8,
      fiber: 4.8,
      sugar: 3.8,
      sodium: 620,
      saturatedFat: 1.0,
      cholesterol: 0,
      vitaminA: 12,
      vitaminC: 8,
      calcium: 52,
      iron: 3.4,
    },
  },
  {
    name: "French Fries (Large)",
    nameAr: "بطاطس محمرة (كبيرة)",
    category: "sides",
    servingSize: 170,
    servingUnit: "g",
    servingDescription: "1 large portion",
    nutrientProfile: {
      calories: 530,
      protein: 5.8,
      carbs: 70.4,
      fat: 25.2,
      fiber: 6.4,
      sugar: 0.8,
      sodium: 360,
      saturatedFat: 4.8,
      cholesterol: 0,
      vitaminA: 0,
      vitaminC: 20,
      calcium: 24,
      iron: 2.0,
    },
  },
  {
    name: "Basturma Eggs",
    nameAr: "بيض بالبسطرمة",
    category: "protein",
    servingSize: 200,
    servingUnit: "g",
    servingDescription: "2 eggs with basturma",
    nutrientProfile: {
      calories: 295,
      protein: 20.4,
      carbs: 2.4,
      fat: 23.2,
      fiber: 0,
      sugar: 1.2,
      sodium: 780,
      saturatedFat: 6.8,
      cholesterol: 385,
      vitaminA: 18,
      vitaminC: 0,
      calcium: 82,
      iron: 3.4,
    },
  },
  {
    name: "Sujuk (Spicy Sausage)",
    nameAr: "سجق",
    category: "protein",
    servingSize: 100,
    servingUnit: "g",
    servingDescription: "3-4 slices",
    nutrientProfile: {
      calories: 310,
      protein: 18.4,
      carbs: 2.8,
      fat: 25.6,
      fiber: 0,
      sugar: 1.2,
      sodium: 880,
      saturatedFat: 9.2,
      cholesterol: 72,
      vitaminA: 4,
      vitaminC: 2,
      calcium: 28,
      iron: 2.4,
    },
  },
  {
    name: "Gebna Makleya",
    nameAr: "جبنة مقلي",
    category: "protein",
    servingSize: 80,
    servingUnit: "g",
    servingDescription: "2-3 pieces",
    nutrientProfile: {
      calories: 245,
      protein: 14.8,
      carbs: 2.4,
      fat: 19.8,
      fiber: 0,
      sugar: 0.8,
      sodium: 620,
      saturatedFat: 12.4,
      cholesterol: 55,
      vitaminA: 8,
      vitaminC: 0,
      calcium: 380,
      iron: 0.8,
    },
  },
  {
    name: "Borani",
    nameAr: "بوراني",
    category: "vegetables",
    servingSize: 150,
    servingUnit: "g",
    servingDescription: "1 bowl",
    nutrientProfile: {
      calories: 110,
      protein: 4.8,
      carbs: 6.8,
      fat: 7.2,
      fiber: 2.4,
      sugar: 4.2,
      sodium: 320,
      saturatedFat: 2.8,
      cholesterol: 12,
      vitaminA: 22,
      vitaminC: 8,
      calcium: 142,
      iron: 1.4,
    },
  },
  {
    name: "Baklava",
    nameAr: "بقلاوة",
    category: "desserts",
    servingSize: 80,
    servingUnit: "g",
    servingDescription: "2 pieces",
    nutrientProfile: {
      calories: 380,
      protein: 6.2,
      carbs: 35.4,
      fat: 25.8,
      fiber: 1.8,
      sugar: 22.4,
      sodium: 110,
      saturatedFat: 4.8,
      cholesterol: 15,
      vitaminA: 4,
      vitaminC: 0,
      calcium: 48,
      iron: 2.2,
    },
  },
  {
    name: "Kahk",
    nameAr: "كحك",
    category: "desserts",
    servingSize: 50,
    servingUnit: "g",
    servingDescription: "3 pieces",
    nutrientProfile: {
      calories: 235,
      protein: 3.8,
      carbs: 28.4,
      fat: 12.6,
      fiber: 0.8,
      sugar: 10.2,
      sodium: 65,
      saturatedFat: 5.8,
      cholesterol: 18,
      vitaminA: 2,
      vitaminC: 0,
      calcium: 22,
      iron: 1.2,
    },
  },
  {
    name: "Roz bil Laban bel Mango",
    nameAr: "رز باللبن بالمانجو",
    category: "desserts",
    servingSize: 300,
    servingUnit: "g",
    servingDescription: "1 large bowl",
    nutrientProfile: {
      calories: 260,
      protein: 6.2,
      carbs: 48.4,
      fat: 5.2,
      fiber: 1.8,
      sugar: 28.2,
      sodium: 95,
      saturatedFat: 3.0,
      cholesterol: 12,
      vitaminA: 38,
      vitaminC: 22,
      calcium: 132,
      iron: 1.2,
    },
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");

    await Food.deleteMany({});
    console.log("Cleared existing foods");

    await Food.insertMany(foods);
    console.log(`Seeded ${foods.length} Egyptian foods`);

    await mongoose.disconnect();
    console.log("Done!");
  } catch (error) {
    console.error("Seed error:", error);
    process.exit(1);
  }
}

seed();
